Library/Library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Library/catalog/urls.py
from django.conf.urls import url
from . import views

app_name = 'catalog'
urlpatterns = [
    url(r'^$', views.index, name='index')

]

Library/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid


class Author(models.Model):
    """
    Model representing an Author.
    """
    Fname = models.CharField(max_length=100)
    Lname = models.CharField(max_length=100)
    Birth = models.DateField('Birth', null=True, blank=True)
    Death = models.DateField('Death', null=True, blank=True)

    def get_absolute_url(self):
        """
        returns The url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, %s' % (self.Fname, self.Lname)


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField('Genre', help_text='Select a genre for this book')
    title = models.CharField(max_length=200)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 character <a href="https://isbn-international.org">ISBN</a>')

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        returns The url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e , that can be borrowed from the library)
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    Loan_status = (
        ('m', 'Maintenance'),
        ('o', 'on loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )
    status = models.CharField(max_length=1, choices=Loan_status, blank=True, default='m', help_text='Book Availability')


class Meta:
    ordering = ['due_back']

    def __str__(self):
        """
        String for representing the Model object.
        """
        return '%s, (%s)' % (self.id, self.book.title)


class Genre(models.Model):
    """
    Model representing a book genre
    """
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc)')

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name

Library/catalog/views.py
from django.shortcuts import render
from . import models


def index(request):
    """
    View function for home page
    """
    # generates count of the some of main object
    num_books = models.Book.objects.all().count()
    num_instances = models.BookInstance.objects.all().count()
    # Available books
    avl_instances = models.BookInstance.objects.filter(status__exact='a').count()
    num_authors = models.Author.objects.count()  # the 'all()' is implied by default

    # Render the 'index.html' with the data in context
    return render(request,
                  'catalog/index.html',
                  context={'num_books': num_books, 'num_instances': num_instances, 'avl_instances': avl_instances,
                           'num_authors': num_authors})

Library/catalog/templates/catalog/base_html.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Local Library</title> {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width-device-width, initial-scale=1" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- Add additional css in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'catalog/style.css'%}">
</head>
<body>
    <div class="container_fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <ul>
                    <li><a href="{% url 'catalog:index' %}">Home</a></li>
                    <li><a href="">All books</a></li>
                    <li><a href="">All authors</a></li>
                </ul>
                {% endblock %}
            </div>
            <div class="col-sm-10">
            {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

Library/catalog/templates/catalog/index.html
{% extends "catalog/base_html.html" %}

{% block  content %}
    <h1>Local Library Home</h1>
        <p>welcome to <em>Local library</em>, a basic Django website.</p>
    <h2>Dynamic content</h2>
        <p>The library has the following record counts </p>
        <ul>
            <li><strong>Books </strong>  {{ num_books }}</li>
            <li><strong>Copies </strong> {{ num_instances }}</li>
            <li><strong>Availability </strong>   {{ avl_instances }}</li>
            <li><strong>Authors </strong>    {{ num_authors }}</li>
        </ul>

{% endblock %}